# Generated by Django 5.1.5 on 2025-01-19 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(unique=True)),
                ('shortened_url', models.CharField(max_length=6, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('expiration_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('shortened_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='shortener.url')),
            ],
        ),
    ]
