# Generated by Django 5.1.5 on 2025-01-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='access_timestamp',
            field=models.DateTimeField(),
        ),
    ]
